In [158]:
import tensorflow as tf
import numpy as np
import scipy.stats

In [3]:
# Set Eager API
print("Setting Eager mode...")
tf.enable_eager_execution()
tfe = tf.contrib.eager

Setting Eager mode...

For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.



In [4]:
a = tf.constant([1., 2., 3., 4., 5., 6.], dtype=tf.float32)
a

<tf.Tensor: id=0, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [5]:
b = tf.constant([2., 3., 4., 5., 6., 7.], dtype=tf.float32)

In [6]:
sigma = tf.constant([2., 3., 4., 5., 6., 7.], dtype=tf.float32)

In [7]:
mu = tf.constant([1., 2., 3., 4., 5., 6.], dtype=tf.float32)

In [8]:
tf.math.reduce_sum(tf.math.square(a))

<tf.Tensor: id=7, shape=(), dtype=float32, numpy=91.0>

In [9]:
tf.reduce_sum(a*b)

<tf.Tensor: id=11, shape=(), dtype=float32, numpy=112.0>

In [10]:
tf.math.reduce_prod(a)

<tf.Tensor: id=14, shape=(), dtype=float32, numpy=720.0>

In [11]:
tf.math.reduce_sum(tf.math.log(a))

<tf.Tensor: id=18, shape=(), dtype=float32, numpy=6.5792513>

In [12]:
n=6

In [13]:
0.5*(- tf.math.reduce_sum(tf.math.log(sigma)) - n + tf.math.reduce_sum(sigma) + tf.math.reduce_sum(tf.math.square(mu)))

<tf.Tensor: id=34, shape=(), dtype=float32, numpy=51.73742>

In [14]:
tf.concat([a,b], 0)

<tf.Tensor: id=37, shape=(12,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 2., 3., 4., 5., 6., 7.], dtype=float32)>

In [15]:
print(tf.Print(a,[a],"a="))

Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:
```python
    sess = tf.Session()
    with sess.as_default():
        tensor = tf.range(10)
        print_op = tf.print(tensor)
        with tf.control_dependencies([print_op]):
          out = tf.add(tensor, tensor)
        sess.run(out)
    ```
Additionally, to use tf.print in python 2.7, users must make sure to import
the following:

  `from __future__ import print_function`

tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32)


In [16]:
a

<tf.Tensor: id=0, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [17]:
t1 = tf.constant([[1.,2.],[1.,2.],[1.,2.]], dtype=tf.float32)
t1.shape
t1

<tf.Tensor: id=42, shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [1., 2.],
       [1., 2.]], dtype=float32)>

In [18]:
t2 = tf.constant([[3.,4.,5.,6.],[3.,4.,5.,6.],[3.,4.,5.,6.]], dtype=tf.float32)
t2.shape

TensorShape([Dimension(3), Dimension(4)])

In [19]:
tf.concat([t1,t2], 1).shape

TensorShape([Dimension(3), Dimension(6)])

In [20]:
aa = tf.constant([[1.,2.],[1.,2.],[1.,2.]], dtype=tf.float32)
bb = tf.constant([[5.,6.],[7.,8.],[9.,10.]], dtype=tf.float32)
aa + bb

<tf.Tensor: id=49, shape=(3, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [ 8., 10.],
       [10., 12.]], dtype=float32)>

In [21]:
tf.eye(10, num_columns=3)

<tf.Tensor: id=57, shape=(10, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [22]:
num_rows = 128
inferred_input_dim = 200

x_new_predictors_inferred = tf.ones([num_rows, inferred_input_dim], tf.float32)
x_given = tf.random.normal(
    shape=(num_rows, 3),
    mean=0.0,
    stddev=1.0,
    dtype=tf.float32,
    seed=None,
    name=None
)


In [23]:
x_all = tf.concat([x_given,x_new_predictors_inferred], 1)

In [24]:
x_all.shape[0].value




128

In [25]:
a

<tf.Tensor: id=0, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [26]:
e = tf.eye(6)

In [27]:
a*e

<tf.Tensor: id=75, shape=(6, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0.],
       [0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 6.]], dtype=float32)>

In [28]:
b

<tf.Tensor: id=2, shape=(6,), dtype=float32, numpy=array([2., 3., 4., 5., 6., 7.], dtype=float32)>

In [29]:
tf.math.multiply(a,b)

<tf.Tensor: id=78, shape=(6,), dtype=float32, numpy=array([ 2.,  6., 12., 20., 30., 42.], dtype=float32)>

In [30]:
a*b

<tf.Tensor: id=80, shape=(6,), dtype=float32, numpy=array([ 2.,  6., 12., 20., 30., 42.], dtype=float32)>

In [31]:
f = tf.ones(6, tf.float32)

In [32]:
f

<tf.Tensor: id=84, shape=(6,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1.], dtype=float32)>

In [33]:
a*f

<tf.Tensor: id=86, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [34]:
x = tf.constant([[1.,1.,1.,1.,1.,1.],[2.,2.,2.,2.,2.,2.],[3.,3.,3.,3.,3.,3.]], dtype=tf.float32)
x.shape

TensorShape([Dimension(3), Dimension(6)])

In [35]:
y = tf.constant([[1.,1.,1.],[2.,2.,2.],[3.,3.,3.]], dtype=tf.float32)
y.shape

TensorShape([Dimension(3), Dimension(3)])

In [36]:
a1 = tf.constant([1., 2., 3., 4., 5., 6.], dtype=tf.float32)
a2 = tf.constant([1., 2., 3.], dtype=tf.float32)

In [37]:
r1 = x*a1

In [38]:
r2 = y*a2

In [39]:
tf.concat([r1,r2], axis=1)

<tf.Tensor: id=95, shape=(3, 9), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.,  1.,  2.,  3.],
       [ 2.,  4.,  6.,  8., 10., 12.,  2.,  4.,  6.],
       [ 3.,  6.,  9., 12., 15., 18.,  3.,  6.,  9.]], dtype=float32)>

In [40]:
x_small = tf.constant([[1.,1.,1.,1.,1.,1.]], dtype=tf.float32)
x_small.shape

TensorShape([Dimension(1), Dimension(6)])

In [41]:
y_small = tf.constant([[1.,1.,1.]], dtype=tf.float32)
y_small.shape

TensorShape([Dimension(1), Dimension(3)])

In [42]:
r1_small = x_small*a1

In [43]:
r2_small = y_small*a2

In [44]:
r1_small,r2_small

(<tf.Tensor: id=99, shape=(1, 6), dtype=float32, numpy=array([[1., 2., 3., 4., 5., 6.]], dtype=float32)>,
 <tf.Tensor: id=100, shape=(1, 3), dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>)

In [45]:
tf.concat([r1_small,r2_small], axis=1)

<tf.Tensor: id=104, shape=(1, 9), dtype=float32, numpy=array([[1., 2., 3., 4., 5., 6., 1., 2., 3.]], dtype=float32)>

In [46]:
a


<tf.Tensor: id=0, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [47]:
a.shape[0].value

6

In [48]:
mean = tf.constant([[1., 2., 3., 4., 5., 6.],
                    [2., 2., 3., 4., 3., 2.],
                    [0., 0., 0., 0., 0., 0.],
                    [1., 2., 1., 1., 2., 1.],
                    [0., 0., 0., 0., 0., 0.]
                   ]
                    , dtype=tf.float32)
std = tf.constant([[6., 2., 8., 4., 1., 6.],
                   [1., 4., 8., 5., 1., 3.],
                   [3., 2., 1., 4., 7., 2.]
                  ]
                  , dtype=tf.float32)

In [49]:
var = tf.square(std)

In [50]:
means_norm = tf.norm(mean, ord='euclidean', axis=1)
means_norm

<tf.Tensor: id=114, shape=(5,), dtype=float32, numpy=
array([9.539392 , 6.78233  , 0.       , 3.4641016, 0.       ],
      dtype=float32)>

In [51]:
means_penalty_relu = tf.nn.relu(-means_norm+1)            
means_penalty_relu

<tf.Tensor: id=119, shape=(5,), dtype=float32, numpy=array([0., 0., 1., 0., 1.], dtype=float32)>

In [52]:
means_penalty = tf.reduce_sum(means_penalty_relu)
means_penalty

<tf.Tensor: id=122, shape=(), dtype=float32, numpy=2.0>

In [53]:
tf.math.log(var)

<tf.Tensor: id=124, shape=(3, 6), dtype=float32, numpy=
array([[3.583519 , 1.3862944, 4.158883 , 2.7725887, 0.       , 3.583519 ],
       [0.       , 2.7725887, 4.158883 , 3.218876 , 0.       , 2.1972246],
       [2.1972246, 1.3862944, 0.       , 2.7725887, 3.8918202, 1.3862944]],
      dtype=float32)>

In [54]:
tf.math.square(mean)

<tf.Tensor: id=126, shape=(5, 6), dtype=float32, numpy=
array([[ 1.,  4.,  9., 16., 25., 36.],
       [ 4.,  4.,  9., 16.,  9.,  4.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  4.,  1.,  1.,  4.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)>

In [55]:
mean**2

<tf.Tensor: id=129, shape=(5, 6), dtype=float32, numpy=
array([[ 1.,  4.,  9., 16., 25., 36.],
       [ 4.,  4.,  9., 16.,  9.,  4.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  4.,  1.,  1.,  4.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)>

In [56]:
inner = 1 + tf.math.log(var) - tf.math.square(mean) - tf.math.square(var)
inner

InvalidArgumentError: Incompatible shapes: [3,6] vs. [5,6] [Op:Sub] name: sub/

In [ ]:
inner = 1 + tf.math.log(var) - mean**2 - var**2
inner

In [57]:
kls = tf.math.reduce_sum(inner, axis=1)
kls

NameError: name 'inner' is not defined

In [58]:
tf.math.reduce_mean(kls)

NameError: name 'kls' is not defined

In [59]:
def calculateKL(mean,std):
	inner = 1 + tf.math.log(std) - mean**2 - std**2
	kls = tf.math.reduce_sum(inner, axis=1)
	return tf.math.reduce_mean(kls)

In [60]:
calculateKL(mean, std)

InvalidArgumentError: Incompatible shapes: [3,6] vs. [5,6] [Op:Sub] name: sub/

In [61]:
probs = tf.constant([[0.1,0.2,0.7],
                      [0.3,0.2,0.5],
                      [0.1,0.5,0.4],
                      [0.1,0.8,0.1]])

In [62]:
def logit(p):
    return tf.log(p/(1-p))

In [63]:
logits = logit(probs)
logits

<tf.Tensor: id=144, shape=(4, 3), dtype=float32, numpy=
array([[-2.1972246 , -1.3862944 ,  0.84729785],
       [-0.8472978 , -1.3862944 ,  0.        ],
       [-2.1972246 ,  0.        , -0.40546516],
       [-2.1972246 ,  1.3862945 , -2.1972246 ]], dtype=float32)>

In [64]:
tf.sigmoid(logit(probs))

<tf.Tensor: id=150, shape=(4, 3), dtype=float32, numpy=
array([[0.09999996, 0.19999999, 0.7       ],
       [0.3       , 0.19999999, 0.5       ],
       [0.09999996, 0.5       , 0.4       ],
       [0.1       , 0.8       , 0.1       ]], dtype=float32)>

In [65]:
y_pred = tf.constant([[0.1,0.2,0.7],
                      [0.3,0.2,0.5],
                      [0.1,0.5,0.4],
                      [0.1,0.8,0.1]])

In [66]:
ber_dist = tf.distributions.Bernoulli(probs=y_pred)

Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.


In [67]:
y_true = tf.constant([[1.,0.,0.],
                      [0.,1.,0.],
                      [1.,0.,0.],
                      [0.,1.,0.]])

In [68]:
tf.nn.sigmoid_cross_entropy_with_logits(labels=y_true, logits=logits)

<tf.Tensor: id=168, shape=(4, 3), dtype=float32, numpy=
array([[2.3025851 , 0.22314355, 1.2039728 ],
       [0.35667497, 1.609438  , 0.6931472 ],
       [2.3025851 , 0.6931472 , 0.5108256 ],
       [0.10536051, 0.22314353, 0.10536051]], dtype=float32)>

In [69]:
tf.nn.softmax_cross_entropy_with_logits_v2(labels=y_true, logits=logits)

<tf.Tensor: id=201, shape=(4,), dtype=float32, numpy=array([3.1884167 , 1.9042375 , 2.7725887 , 0.05406725], dtype=float32)>

In [126]:
logits
tf.nn.softmax(logits=logits, axis=0)

<tf.Tensor: id=443, shape=(4, 3), dtype=float32, numpy=
array([[0.14583333, 0.04545455, 0.5675676 ],
       [0.56250006, 0.04545455, 0.24324325],
       [0.14583333, 0.18181817, 0.16216215],
       [0.14583333, 0.72727275, 0.02702703]], dtype=float32)>

In [70]:
-tf.reduce_sum(tf.nn.sigmoid_cross_entropy_with_logits(labels=y_true, logits=logits), axis=1)

<tf.Tensor: id=215, shape=(4,), dtype=float32, numpy=array([-3.7297015 , -2.65926   , -3.506558  , -0.43386453], dtype=float32)>

In [71]:
ber_dist.log_prob(y_true)

<tf.Tensor: id=227, shape=(4, 3), dtype=float32, numpy=
array([[-2.3025851 , -0.22314355, -1.2039728 ],
       [-0.35667494, -1.609438  , -0.6931472 ],
       [-2.3025851 , -0.6931472 , -0.51082563],
       [-0.10536051, -0.22314355, -0.10536051]], dtype=float32)>

In [72]:
tf.exp(tf.reduce_sum(ber_dist.log_prob(1e-10 + y_true)))

<tf.Tensor: id=244, shape=(), dtype=float32, numpy=3.2659205e-05>

In [73]:
1-y_true

<tf.Tensor: id=247, shape=(4, 3), dtype=float32, numpy=
array([[0., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.]], dtype=float32)>

In [74]:
y_true*tf.log(y_pred) + (1-y_true)*tf.log(1-y_pred)

<tf.Tensor: id=257, shape=(4, 3), dtype=float32, numpy=
array([[-2.3025851 , -0.22314353, -1.2039728 ],
       [-0.35667497, -1.609438  , -0.6931472 ],
       [-2.3025851 , -0.6931472 , -0.5108256 ],
       [-0.10536055, -0.22314353, -0.10536055]], dtype=float32)>

In [75]:
tf.exp(tf.reduce_sum(y_true*tf.log(y_pred) + (1-y_true)*tf.log(1-y_pred)))

<tf.Tensor: id=270, shape=(), dtype=float32, numpy=3.2659205e-05>

In [76]:
0.9*0.8*0.7

0.504

In [77]:
np_a = np.array([[1,2,3,4,5],
                 [2,3,4,5,6],
                 [3,4,5,6,7]
                ])

In [78]:
np_y = np.array([1,2,3])

In [79]:
np_a

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [80]:
np_a[1:3]

array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [81]:
np_y[1:3]

array([2, 3])

In [82]:
tf.random.normal(
    shape=(1,5),
    mean=5.0,
    stddev=2.0
)

<tf.Tensor: id=277, shape=(1, 5), dtype=float32, numpy=
array([[6.4223166, 4.45996  , 5.601477 , 4.2868333, 5.8136244]],
      dtype=float32)>

In [117]:
current_value = tf.constant([
    [3.,4.,5.,6.,7.,8.,9.,10.],
    [3.,4.,5.,6.,7.,8.,9.,10.],
    [3.,4.,5.,6.,7.,8.,9.,10.]
], dtype=tf.float32)
norm_params.shape

TensorShape([Dimension(3), Dimension(8)])

In [118]:
middle_layer_dim=2

In [119]:
means1 = current_value[:, :middle_layer_dim]

In [120]:
stdevs1 = tf.nn.softplus(current_value[:, middle_layer_dim:(middle_layer_dim*2)]) + 1e-6

In [121]:
means2 = current_value[:, (middle_layer_dim*2):(middle_layer_dim*3)]

In [122]:
stdevs2 = tf.nn.softplus(current_value[:, (middle_layer_dim*3):(middle_layer_dim*4)]) + 1e-6

In [85]:
norm_params

<tf.Tensor: id=279, shape=(3, 4), dtype=float32, numpy=
array([[3., 4., 5., 6.],
       [3., 4., 5., 6.],
       [3., 4., 5., 6.]], dtype=float32)>

In [84]:
norm_params[:,:2]

<tf.Tensor: id=283, shape=(3, 2), dtype=float32, numpy=
array([[3., 4.],
       [3., 4.],
       [3., 4.]], dtype=float32)>

In [86]:
norm_params[:,2:]

<tf.Tensor: id=289, shape=(3, 2), dtype=float32, numpy=
array([[5., 6.],
       [5., 6.],
       [5., 6.]], dtype=float32)>

In [96]:
indexes = tf.constant([1, 2])
norm_params[:,indexes]

TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got <tf.Tensor: id=324, shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [129]:
eps1 = tf.random_normal(shape=(10,2), mean=0, stddev=1, 
                               dtype=tf.float32)
eps2 = tf.random_normal(shape=(10,2), mean=0, stddev=1, 
                               dtype=tf.float32)

In [130]:
eps1

<tf.Tensor: id=465, shape=(10, 2), dtype=float32, numpy=
array([[-0.98303866,  0.17387082],
       [-1.7655772 ,  0.70335376],
       [ 1.5072902 ,  0.6649761 ],
       [ 1.2220899 ,  0.39191774],
       [-0.6027583 , -1.3779223 ],
       [-0.84137094, -0.7731898 ],
       [ 0.68443716, -1.40442   ],
       [-0.41767552,  0.78373134],
       [ 0.38205168, -1.7449099 ],
       [ 0.16932958,  0.84655076]], dtype=float32)>

In [144]:
means1, stdevs1 = tf.constant([0.,3.]), tf.constant([2.,3.])

In [145]:
tf.add(means1,  stdevs1* eps1)

<tf.Tensor: id=492, shape=(10, 2), dtype=float32, numpy=
array([[-1.9660773 ,  3.5216124 ],
       [-3.5311544 ,  5.110061  ],
       [ 3.0145805 ,  4.9949284 ],
       [ 2.4441798 ,  4.175753  ],
       [-1.2055166 , -1.1337671 ],
       [-1.6827419 ,  0.68043065],
       [ 1.3688743 , -1.2132602 ],
       [-0.83535105,  5.351194  ],
       [ 0.76410335, -2.2347298 ],
       [ 0.33865917,  5.5396523 ]], dtype=float32)>

In [146]:
means1, stdevs1 = tf.constant([0.,3.]), tf.constant([2.,3.])
means2, stdevs2 = tf.constant([1.,5.]), tf.constant([1.5,3.1])

In [148]:
0.5*tf.add(means1,  stdevs1* eps1) + 0.5*tf.add(means2,  stdevs2* eps2)

<tf.Tensor: id=516, shape=(10, 2), dtype=float32, numpy=
array([[-1.2203176 ,  4.530306  ],
       [-2.58976   ,  6.145229  ],
       [ 3.1377578 ,  6.0281773 ],
       [ 2.6386573 ,  5.1953487 ],
       [-0.554827  , -0.20266294],
       [-0.9723991 ,  1.6417712 ],
       [ 1.697765  , -0.28348112],
       [-0.23093218,  6.390381  ],
       [ 1.1685904 , -1.3219752 ],
       [ 0.79632676,  6.5819798 ]], dtype=float32)>

In [151]:
dist = tf.distributions.Normal(loc=0., scale=3.)

Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.


In [160]:
dist.prob(0)

<tf.Tensor: id=567, shape=(), dtype=float32, numpy=0.13298075>

In [159]:
scipy.stats.norm.pdf(0, loc=0.0, scale=3.0)

0.1329807601338109

In [ ]:
def norm_const(z, beta1, means1, stdevs1, beta2, means2, stdevs2):
    norm = beta1*mult_dist_1.prob(z) + beta2 * mult_dist_2.prob(z)
    return norm

In [ ]:
def responsibilities(z, beta1, means1, stdevs1, beta2, means2, stdevs2):
    mult_dist_1 = tf.contrib.distributions.MultivariateNormalDiag(loc=means1, scale_diag=stdevs1)
    mult_dist_2 = tf.contrib.distributions.MultivariateNormalDiag(loc=means2, scale_diag=stdevs2)
    nom1 = beta1 * mult_dist_1.prob(z)
    nom2 = beta2 * mult_dist_2.prob(z)
    denom = nom1 + nom2
    return nom1/denom, nom2/denom

In [204]:
def penalty_term(z):
    means1, stdevs1 = tf.constant([2.,0.]), tf.constant([1.,1.])
    means2, stdevs2 = tf.constant([-2.,0.]), tf.constant([1.,1.])
    beta1 = 0.5
    beta2 = 0.5
        
    mult_dist_1 = tf.contrib.distributions.MultivariateNormalDiag(loc=means1, scale_diag=stdevs1)
    mult_dist_2 = tf.contrib.distributions.MultivariateNormalDiag(loc=means2, scale_diag=stdevs2)
    mix_dist = beta1 * mult_dist_1.prob(z) + beta2 * mult_dist_2.prob(z) + 1e-6
    return tf.reduce_sum(tf.log(mix_dist))

In [205]:
z=[0.,3.]
penalty_term(z)

<tf.Tensor: id=6063, shape=(), dtype=float32, numpy=-8.333707>

In [178]:
means1, stdevs1 = tf.constant([2.,0.]), tf.constant([0.07,0.007])
means2, stdevs2 = tf.constant([-2.,0.]), tf.constant([0.07,0.007])
beta1 = 0.5
beta2 = 0.5

In [180]:
mult_dist_1 = tf.contrib.distributions.MultivariateNormalDiag(loc=means1, scale_diag=stdevs1)

In [181]:
mult_dist_2 = tf.contrib.distributions.MultivariateNormalDiag(loc=means2, scale_diag=stdevs2)

In [185]:
mix_dist = beta1 * mult_dist_1.prob(z) + beta2 * mult_dist_2.prob(z)
mix_dist

<tf.Tensor: id=2823, shape=(), dtype=float32, numpy=0.0>

In [187]:
mult_dist_1.prob([0.,3.])

<tf.Tensor: id=3006, shape=(), dtype=float32, numpy=0.0>

In [175]:
tf.reduce_sum(tf.log(, [4.,0.], [0.,1.]])))

<tf.Tensor: id=1369, shape=(), dtype=float32, numpy=-12.027799>

In [195]:
tf.contrib.distributions.MultivariateNormalDiag(loc=[3.,2.], scale_diag=[0.1,2.0]).prob([1.,0.])

<tf.Tensor: id=4071, shape=(), dtype=float32, numpy=0.0>

In [206]:
d = [2.,4.]

In [207]:
d

[2.0, 4.0]

In [208]:
tf.diag(d)

<tf.Tensor: id=6066, shape=(2, 2), dtype=float32, numpy=
array([[2., 0.],
       [0., 4.]], dtype=float32)>

In [212]:
tf.ones(2)/d

<tf.Tensor: id=6072, shape=(2,), dtype=float32, numpy=array([0.5 , 0.25], dtype=float32)>

In [213]:
tf.diag(tf.ones(2)/d)

<tf.Tensor: id=6079, shape=(2, 2), dtype=float32, numpy=
array([[0.5 , 0.  ],
       [0.  , 0.25]], dtype=float32)>

In [223]:
xx = tf.constant([1.,4.,3.])
xx

<tf.Tensor: id=6100, shape=(3,), dtype=float32, numpy=array([1., 4., 3.], dtype=float32)>

In [284]:
@tf.custom_gradient
def log1pexp(x):
    e = tf.log(1 + tf.exp(x))
    def grad(dy):
        print("grad={}".format(dy))
        return (1 - 1 / (1 +  tf.exp(x)))
    return e, grad

In [289]:
@tf.custom_gradient
def log1pexp2(x):
    e = tf.log(1 + tf.exp(x))
    def grad(dy):
        print("grad={}".format(dy))
        return (1 - 1 / (1 +  tf.exp(x)))
    return e, grad

In [290]:
grad_log1pexp = tfe.gradients_function(log1pexp)
grad_log1pexp2 = tfe.gradients_function(log1pexp2)

In [286]:
grad_log1pexp

<function tensorflow.python.eager.backprop.gradients_function.<locals>.decorated(*args, **kwds)>

In [287]:
xx_square = tf.square(xx)

<tf.Tensor: id=6387, shape=(3,), dtype=float32, numpy=array([ 1., 16.,  9.], dtype=float32)>

In [291]:
grad_log1pexp(xx)[0].numpy()

grad=[1. 1. 1.]


array([0.7310586 , 0.98201376, 0.95257413], dtype=float32)

In [307]:
grad_log1pexp2(tf.log(xx))[0].numpy()

grad=[1. 1. 1.]


array([0.5 , 0.8 , 0.75], dtype=float32)

In [296]:
def f1(A,x):
    y=tf.matmul(A,x,name='y')
    return y

In [233]:
x = tf.constant(100.)
y = log1pexp(x)
dy = tf.gradients(y, x)

RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.

In [315]:
@tf.custom_gradient
def f2(A,x):
    y=f1(A,x)
    def grad(dzByDy): # dz/dy = 2y reaches here correctly.
        print("dzByDy={}".format(dzByDy))
        dzByDx=tf.matmul(A,dzByDy,transpose_a=True) 
        return None,dzByDx
    return y,grad

In [316]:
x= tf.constant([[1.],[0.]],name='x')
A= tf.constant([ [1., 2.], [3., 4.]],name='A')

In [317]:
#y=f1(A,x) # This works as desired
y=f2(A,x) #This line gives Erro

In [318]:
z=tf.reduce_sum(y*y,name='z')

In [325]:
grad_f1 = tfe.gradients_function(f2)

In [326]:
grad_f1(A, x)

dzByDy=[[1.]
 [1.]]


[None, <tf.Tensor: id=6520, shape=(2, 1), dtype=float32, numpy=
 array([[4.],
        [6.]], dtype=float32)>]

In [580]:
@tf.custom_gradient
def penalty_term_with_gd(z):
    mean = 20.0
    means1, stdevs1 = tf.constant([0.,mean]), tf.constant([0.7,7.])
    means2, stdevs2 = tf.constant([mean,0.]), tf.constant([7.,0.7])
    means3, stdevs3 = tf.constant([0.,-mean]), tf.constant([0.7,7.])
    means4, stdevs4 = tf.constant([-mean,0.]), tf.constant([7.,0.7])
    beta1 = 0.5
    beta2 = 0.5
    beta3 = 0.5
    beta4 = 0.5
    mult_dist_1 = tf.contrib.distributions.MultivariateNormalDiag(loc=means1, scale_diag=stdevs1)
    mult_dist_2 = tf.contrib.distributions.MultivariateNormalDiag(loc=means2, scale_diag=stdevs2)
    mult_dist_3 = tf.contrib.distributions.MultivariateNormalDiag(loc=means3, scale_diag=stdevs3)
    mult_dist_4 = tf.contrib.distributions.MultivariateNormalDiag(loc=means4, scale_diag=stdevs4)
    stdevs1_inv = tf.diag(tf.ones(2)/stdevs1)
    stdevs2_inv = tf.diag(tf.ones(2)/stdevs2)
    stdevs3_inv = tf.diag(tf.ones(2)/stdevs3)
    stdevs4_inv = tf.diag(tf.ones(2)/stdevs4)

    denom = beta1 * mult_dist_1.prob(z) + beta2 * mult_dist_2.prob(z) + beta3 * mult_dist_3.prob(z) + beta4 * mult_dist_4.prob(z) + 1e-6
    denom = tf.reshape(denom, (-1, 1))
    y=-tf.reduce_sum(tf.log(mix_dist))
        
    def grad(dz): 
        c1 = beta1 * tf.reshape(mult_dist_1.prob(z), (-1, 1)) * tf.matmul((z - means1), stdevs1_inv)
        c2 = beta2 * tf.reshape(mult_dist_2.prob(z), (-1, 1)) * tf.matmul((z - means2), stdevs2_inv)
            
        c3 = beta3 * tf.reshape(mult_dist_3.prob(z), (-1, 1)) * tf.matmul((z - means3), stdevs3_inv)
        c4 = beta4 * tf.reshape(mult_dist_4.prob(z), (-1, 1)) * tf.matmul((z - means4), stdevs4_inv)
        num = c1 + c2 + c3 + c4     
        
        gradient = num/denom
        return dz * gradient
    return y,grad

In [665]:
z = tf.constant([[1., 4.],
                 [3.,1.],
                 [2.,3.],
                 [0.5,0.5],
                 [0.2,2.1]
                ],name='z')
#z = tf.constant([[1., 4.]],name='z')
z

<tf.Tensor: id=35811, shape=(5, 2), dtype=float32, numpy=
array([[1. , 4. ],
       [3. , 1. ],
       [2. , 3. ],
       [0.5, 0.5],
       [0.2, 2.1]], dtype=float32)>

In [358]:
tf.reshape(mult_dist_1.prob(z), (-1, 1))

<tf.Tensor: id=8051, shape=(5, 1), dtype=float32, numpy=
array([[8.5897953e-04],
       [8.3831317e-08],
       [2.8725528e-05],
       [5.1967008e-04],
       [1.1857044e-03]], dtype=float32)>

In [529]:
beta1 * tf.reshape(mult_dist_1.prob(z), (-1, 1)) * tf.matmul((z - means1), stdevs1_inv)

<tf.Tensor: id=24063, shape=(1, 2), dtype=float32, numpy=array([[ 0.00061356, -0.00098169]], dtype=float32)>

In [525]:
c1 = beta1 * tf.reshape(mult_dist_1.prob(z), (-1, 1)) * tf.matmul((z - means1), stdevs1_inv)
c2 = beta2 * tf.reshape(mult_dist_2.prob(z), (-1, 1)) * tf.matmul((z - means2), stdevs2_inv)
c3 = beta3 * tf.reshape(mult_dist_3.prob(z), (-1, 1)) * tf.matmul((z - means3), stdevs3_inv)
c4 = beta4 * tf.reshape(mult_dist_4.prob(z), (-1, 1)) * tf.matmul((z - means4), stdevs4_inv)
num = c1 + c2 + c3 + c4
num

<tf.Tensor: id=23937, shape=(1, 2), dtype=float32, numpy=array([[ 0.00061356, -0.00098169]], dtype=float32)>

In [531]:
c3

<tf.Tensor: id=23837, shape=(1, 2), dtype=float32, numpy=array([[-8.9934987e-10,  1.8933681e-11]], dtype=float32)>

In [508]:
stdevs1_inv

<tf.Tensor: id=6850, shape=(2, 2), dtype=float32, numpy=
array([[1.4285715 , 0.        ],
       [0.        , 0.14285715]], dtype=float32)>

In [343]:
(z - means1)

<tf.Tensor: id=7650, shape=(5, 2), dtype=float32, numpy=
array([[  1. , -16. ],
       [  3. , -19. ],
       [  2. , -17. ],
       [  0.5, -19.5],
       [  0.2, -17.9]], dtype=float32)>

In [347]:
-16*0.14

-2.24

In [341]:
beta1*mult_dist_1.prob(z)

<tf.Tensor: id=7647, shape=(5,), dtype=float32, numpy=
array([4.2948977e-04, 4.1915658e-08, 1.4362764e-05, 2.5983504e-04,
       5.9285219e-04], dtype=float32)>

In [364]:
denom = beta1 * mult_dist_1.prob(z) + beta2 * mult_dist_2.prob(z) + beta3 * mult_dist_3.prob(z) + beta4 * mult_dist_4.prob(z) + 1e-6
denom = tf.reshape(denom, (-1, 1))
denom

<tf.Tensor: id=8371, shape=(5, 1), dtype=float32, numpy=
array([[4.4688999e-04],
       [3.3425156e-04],
       [1.6676533e-05],
       [8.6618331e-04],
       [7.0672878e-04]], dtype=float32)>

In [365]:
num/denom

<tf.Tensor: id=8373, shape=(5, 2), dtype=float32, numpy=
array([[ 1.4253745 , -2.0708935 ],
       [-1.9671723 ,  1.4238652 ],
       [ 2.6661174 , -1.828392  ],
       [ 0.10517165,  0.10517165],
       [ 0.28107592, -1.6422143 ]], dtype=float32)>

In [378]:
grad_penalty = tfe.gradients_function(penalty_term_with_gd)

In [379]:
grad_penalty(z)

[<tf.Tensor: id=10760, shape=(5, 2), dtype=float32, numpy=
 array([[ 1.4253745 , -2.0708935 ],
        [-1.9671723 ,  1.4238652 ],
        [ 2.6661174 , -1.828392  ],
        [ 0.10517165,  0.10517165],
        [ 0.28107592, -1.6422143 ]], dtype=float32)>]

In [503]:
penalty_term_with_gd(z)

TypeError: penalty_term_with_gd() missing 1 required positional argument: 'dists'

In [598]:
mean=20.0
mean_of_oblique=np.sqrt((mean*mean) / 2)

# var=0.05
# var_of_oblique=var/np.sqrt(2)

mean1, cov1 = [0,mean], [0.7,7.0]

mean2, cov2 = [mean_of_oblique,mean_of_oblique], np.array([
    [5.0,4.0],
    [4.0,5.0]
])

mean3, cov3 = [mean,0], [7.0,0.7]

mean4, cov4 = [mean_of_oblique,-mean_of_oblique], np.array([
    [5.0,-4.0],
    [-4.0,5.0]
])

mean5, cov5 = [0,-mean], [0.7,7.0]

mean6, cov6 = [-mean_of_oblique,-mean_of_oblique], np.array([
    [5.0,4.0],
    [4.0,5.0]
])

mean7, cov7 = [-mean,0], [7.0,0.7]

mean8, cov8 = [-mean_of_oblique,mean_of_oblique], np.array([
    [5.0,-4.0],
    [-4.0,5.0]
])

In [599]:
len(mean8)

2

In [600]:
class NormDistDiag():
    
    def __init__(self, mean, stdev, beta):
        self.mean = mean
        self.stdev = stdev
        self.beta = beta
        self.tf_mean, self.tf_stdev = tf.constant(self.mean), tf.constant(self.stdev)
        self.tf_dist = tf.contrib.distributions.MultivariateNormalDiag(loc=self.tf_mean, scale_diag=self.tf_stdev)
        self.dim = len(mean)
        
    def tf_dist(self):
        return self.tf_dist

    def prob(self, z):
        return self.tf_dist.prob(z)
        
    def stdev_inv(self):
        return tf.diag(tf.ones(self.dim)/self.stdev)
        
    def grad_component(self, z):
        return self.beta * tf.reshape(self.prob(z), (-1, 1)) * tf.matmul((z - self.tf_mean), self.stdev_inv())
    

In [629]:
dist1 = NormDistDiag(mean1, cov1, 0.5)
dist3 = NormDistDiag(mean3, cov3, 0.5)
dist5 = NormDistDiag(mean5, cov5, 0.5)
dist7 = NormDistDiag(mean7, cov7, 0.5)

In [630]:
dists = [dist1, dist3, dist5, dist7]

In [611]:
#@tf.custom_gradient
def penalty_term_with_gd(z, dists):
    probs = tf.stack([dist.prob(z) for dist in dists])
    betas = tf.constant([dist.beta for dist in dists], shape=(len(dists),1))
    denom = tf.reduce_sum(betas * probs, axis=0)
    denom = tf.reshape(denom, (-1, 1))
    y=-tf.reduce_sum(tf.log(denom))
        
    def grad(dz): 
        grad_components = tf.stack([dist.grad_component(z) for dist in dists])
        num = tf.reduce_sum(grad_components, axis=2)
        
        gradient = num/denom
        return dz * gradient
    return y,grad

In [613]:
penalty_term_with_gd(z, dists)

(<tf.Tensor: id=31384, shape=(), dtype=float32, numpy=41.094246>,
 <function __main__.penalty_term_with_gd.<locals>.grad(dz)>)

In [639]:
mean = 20.0
means1, stdevs1 = tf.constant(mean1), tf.constant([0.7,7.])
means3, stdevs3 = tf.constant(mean3), tf.constant([7.,0.7])
means5, stdevs5 = tf.constant(mean5), tf.constant([0.7,7.])
means7, stdevs7 = tf.constant(mean7), tf.constant([7.,0.7])
    
#betas = [0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]
betas = tf.constant([0.5,0.5,0.5,0.5], shape=(4,1))

mult_dist_1 = tf.contrib.distributions.MultivariateNormalDiag(loc=means1, scale_diag=stdevs1)
mult_dist_3 = tf.contrib.distributions.MultivariateNormalDiag(loc=means3, scale_diag=stdevs3)
mult_dist_5 = tf.contrib.distributions.MultivariateNormalDiag(loc=means5, scale_diag=stdevs5)
mult_dist_7 = tf.contrib.distributions.MultivariateNormalDiag(loc=means7, scale_diag=stdevs7)
    
stdevs1_inv = tf.diag(tf.ones(2)/stdevs1)
stdevs3_inv = tf.diag(tf.ones(2)/stdevs3)
stdevs5_inv = tf.diag(tf.ones(2)/stdevs5)
stdevs7_inv = tf.diag(tf.ones(2)/stdevs7)

In [631]:
betas = tf.constant([dist.beta for dist in dists], shape=(len(dists),1))

In [642]:
denom = tf.reduce_sum(betas * probs, axis=0)
denom = tf.reshape(denom, (-1, 1))
denom

<tf.Tensor: id=34761, shape=(5, 1), dtype=float32, numpy=
array([[4.4588998e-04],
       [3.3325155e-04],
       [1.5676533e-05],
       [8.6518330e-04],
       [7.0572877e-04]], dtype=float32)>

In [643]:
c1 = beta1 * tf.reshape(mult_dist_1.prob(z), (-1, 1)) * tf.matmul((z - means1), stdevs1_inv)
c2 = beta2 * tf.reshape(mult_dist_3.prob(z), (-1, 1)) * tf.matmul((z - means3), stdevs3_inv)
c3 = beta3 * tf.reshape(mult_dist_5.prob(z), (-1, 1)) * tf.matmul((z - means5), stdevs5_inv)
c4 = beta4 * tf.reshape(mult_dist_7.prob(z), (-1, 1)) * tf.matmul((z - means7), stdevs7_inv)
num = c1 + c2 + c3 + c4
num

<tf.Tensor: id=34861, shape=(5, 2), dtype=float32, numpy=
array([[ 6.3698558e-04, -9.2546153e-04],
       [-6.5753039e-04,  4.7592915e-04],
       [ 4.4461594e-05, -3.0491239e-05],
       [ 9.1097929e-05,  9.1097929e-05],
       [ 1.9864445e-04, -1.1606001e-03]], dtype=float32)>

In [644]:
num/denom

<tf.Tensor: id=34863, shape=(5, 2), dtype=float32, numpy=
array([[ 1.4285712 , -2.075538  ],
       [-1.9730753 ,  1.4281379 ],
       [ 2.836188  , -1.9450245 ],
       [ 0.10529321,  0.10529321],
       [ 0.28147423, -1.6445413 ]], dtype=float32)>

In [706]:
class NormDist():
    
    def __init__(self, mean, stdev, beta):
        self.mean = mean
        self.stdev = stdev
        self.beta = beta
        self.tf_mean, self.tf_stdev = tf.constant(self.mean), tf.constant(self.stdev)
        self.tf_dist = tf.contrib.distributions.MultivariateNormalFullCovariance(loc=self.tf_mean, covariance_matrix=self.tf_stdev)
        self.dim = len(mean)
        
    def tf_dist(self):
        return self.tf_dist

    def prob(self, z):
        return tf.cast(self.tf_dist.prob(tf.cast(z, tf.float64)), tf.float32)
        
    def stdev_inv(self):
        return tf.diag(tf.ones(self.dim)/self.stdev)
        
    def grad_component(self, z):
        return self.beta * tf.reshape(self.prob(z), (-1, 1)) * tf.matmul((z - self.tf_mean), self.stdev_inv())

In [707]:
dist2 = NormDist(mean2, cov2, 0.5)
dist4 = NormDist(mean4, cov4, 0.5)
dist6 = NormDist(mean6, cov6, 0.5)
dist8 = NormDist(mean8, cov8, 0.5)

In [704]:
#dists = [dist2, dist4, dist6, dist8]
dists = [dist1, dist2, dist3, dist4, dist5, dist6, dist7, dist8]
#dists = [dist1, dist3, dist5, dist7]

In [705]:
penalty_term_with_gd(z, dists)

(<tf.Tensor: id=40554, shape=(), dtype=float32, numpy=41.093864>,
 <function __main__.penalty_term_with_gd.<locals>.grad(dz)>)