In [171]:
import tensorflow as tf
import numpy as np

In [2]:
# Set Eager API
print("Setting Eager mode...")
tf.enable_eager_execution()
tfe = tf.contrib.eager

Setting Eager mode...

For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.



In [3]:
a = tf.constant([1., 2., 3., 4., 5., 6.], dtype=tf.float32)
a

<tf.Tensor: id=0, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [4]:
b = tf.constant([2., 3., 4., 5., 6., 7.], dtype=tf.float32)

In [5]:
sigma = tf.constant([2., 3., 4., 5., 6., 7.], dtype=tf.float32)

In [6]:
mu = tf.constant([1., 2., 3., 4., 5., 6.], dtype=tf.float32)

In [7]:
tf.math.reduce_sum(tf.math.square(a))

<tf.Tensor: id=7, shape=(), dtype=float32, numpy=91.0>

In [8]:
tf.reduce_sum(a*b)

<tf.Tensor: id=11, shape=(), dtype=float32, numpy=112.0>

In [9]:
tf.math.reduce_prod(a)

<tf.Tensor: id=14, shape=(), dtype=float32, numpy=720.0>

In [10]:
tf.math.reduce_sum(tf.math.log(a))

<tf.Tensor: id=18, shape=(), dtype=float32, numpy=6.5792513>

In [11]:
n=6

In [12]:
0.5*(- tf.math.reduce_sum(tf.math.log(sigma)) - n + tf.math.reduce_sum(sigma) + tf.math.reduce_sum(tf.math.square(mu)))

<tf.Tensor: id=34, shape=(), dtype=float32, numpy=51.73742>

In [13]:
tf.concat([a,b], 0)

<tf.Tensor: id=37, shape=(12,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 2., 3., 4., 5., 6., 7.], dtype=float32)>

In [14]:
print(tf.Print(a,[a],"a="))

Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:
```python
    sess = tf.Session()
    with sess.as_default():
        tensor = tf.range(10)
        print_op = tf.print(tensor)
        with tf.control_dependencies([print_op]):
          out = tf.add(tensor, tensor)
        sess.run(out)
    ```
Additionally, to use tf.print in python 2.7, users must make sure to import
the following:

  `from __future__ import print_function`

tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32)


In [15]:
a

<tf.Tensor: id=0, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [16]:
t1 = tf.constant([[1.,2.],[1.,2.],[1.,2.]], dtype=tf.float32)
t1.shape
t1

<tf.Tensor: id=42, shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [1., 2.],
       [1., 2.]], dtype=float32)>

In [17]:
t2 = tf.constant([[3.,4.,5.,6.],[3.,4.,5.,6.],[3.,4.,5.,6.]], dtype=tf.float32)
t2.shape

TensorShape([Dimension(3), Dimension(4)])

In [18]:
tf.concat([t1,t2], 1).shape

TensorShape([Dimension(3), Dimension(6)])

In [19]:
aa = tf.constant([[1.,2.],[1.,2.],[1.,2.]], dtype=tf.float32)
bb = tf.constant([[5.,6.],[7.,8.],[9.,10.]], dtype=tf.float32)
aa + bb

<tf.Tensor: id=49, shape=(3, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [ 8., 10.],
       [10., 12.]], dtype=float32)>

In [20]:
tf.eye(10, num_columns=3)

<tf.Tensor: id=57, shape=(10, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [21]:
num_rows = 128
inferred_input_dim = 200

x_new_predictors_inferred = tf.ones([num_rows, inferred_input_dim], tf.float32)
x_given = tf.random.normal(
    shape=(num_rows, 3),
    mean=0.0,
    stddev=1.0,
    dtype=tf.float32,
    seed=None,
    name=None
)


In [22]:
x_all = tf.concat([x_given,x_new_predictors_inferred], 1)

In [23]:
x_all.shape[0].value




128

In [24]:
a

<tf.Tensor: id=0, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [25]:
e = tf.eye(6)

In [26]:
a*e

<tf.Tensor: id=75, shape=(6, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0.],
       [0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 6.]], dtype=float32)>

In [27]:
b

<tf.Tensor: id=2, shape=(6,), dtype=float32, numpy=array([2., 3., 4., 5., 6., 7.], dtype=float32)>

In [28]:
tf.math.multiply(a,b)

<tf.Tensor: id=78, shape=(6,), dtype=float32, numpy=array([ 2.,  6., 12., 20., 30., 42.], dtype=float32)>

In [29]:
a*b

<tf.Tensor: id=80, shape=(6,), dtype=float32, numpy=array([ 2.,  6., 12., 20., 30., 42.], dtype=float32)>

In [30]:
f = tf.ones(6, tf.float32)

In [31]:
f

<tf.Tensor: id=84, shape=(6,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1.], dtype=float32)>

In [32]:
a*f

<tf.Tensor: id=86, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [33]:
x = tf.constant([[1.,1.,1.,1.,1.,1.],[2.,2.,2.,2.,2.,2.],[3.,3.,3.,3.,3.,3.]], dtype=tf.float32)
x.shape

TensorShape([Dimension(3), Dimension(6)])

In [34]:
y = tf.constant([[1.,1.,1.],[2.,2.,2.],[3.,3.,3.]], dtype=tf.float32)
y.shape

TensorShape([Dimension(3), Dimension(3)])

In [35]:
a1 = tf.constant([1., 2., 3., 4., 5., 6.], dtype=tf.float32)
a2 = tf.constant([1., 2., 3.], dtype=tf.float32)

In [36]:
r1 = x*a1

In [37]:
r2 = y*a2

In [38]:
tf.concat([r1,r2], axis=1)

<tf.Tensor: id=95, shape=(3, 9), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.,  1.,  2.,  3.],
       [ 2.,  4.,  6.,  8., 10., 12.,  2.,  4.,  6.],
       [ 3.,  6.,  9., 12., 15., 18.,  3.,  6.,  9.]], dtype=float32)>

In [39]:
x_small = tf.constant([[1.,1.,1.,1.,1.,1.]], dtype=tf.float32)
x_small.shape

TensorShape([Dimension(1), Dimension(6)])

In [40]:
y_small = tf.constant([[1.,1.,1.]], dtype=tf.float32)
y_small.shape

TensorShape([Dimension(1), Dimension(3)])

In [41]:
r1_small = x_small*a1

In [42]:
r2_small = y_small*a2

In [43]:
r1_small,r2_small

(<tf.Tensor: id=99, shape=(1, 6), dtype=float32, numpy=array([[1., 2., 3., 4., 5., 6.]], dtype=float32)>,
 <tf.Tensor: id=100, shape=(1, 3), dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>)

In [44]:
tf.concat([r1_small,r2_small], axis=1)

<tf.Tensor: id=104, shape=(1, 9), dtype=float32, numpy=array([[1., 2., 3., 4., 5., 6., 1., 2., 3.]], dtype=float32)>

In [45]:
a


<tf.Tensor: id=0, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [46]:
a.shape[0].value

6

In [47]:
mean = tf.constant([[1., 2., 3., 4., 5., 6.],
                    [2., 2., 3., 4., 3., 2.],
                    [1., 2., 1., 1., 2., 1.]
                   ]
                    , dtype=tf.float32)
std = tf.constant([[6., 2., 8., 4., 1., 6.],
                   [1., 4., 8., 5., 1., 3.],
                   [3., 2., 1., 4., 7., 2.]
                  ]
                  , dtype=tf.float32)

In [53]:
var = tf.square(std)

In [54]:
mean

<tf.Tensor: id=107, shape=(3, 6), dtype=float32, numpy=
array([[1., 2., 3., 4., 5., 6.],
       [2., 2., 3., 4., 3., 2.],
       [1., 2., 1., 1., 2., 1.]], dtype=float32)>

In [55]:
tf.math.log(var)

<tf.Tensor: id=117, shape=(3, 6), dtype=float32, numpy=
array([[3.583519 , 1.3862944, 4.158883 , 2.7725887, 0.       , 3.583519 ],
       [0.       , 2.7725887, 4.158883 , 3.218876 , 0.       , 2.1972246],
       [2.1972246, 1.3862944, 0.       , 2.7725887, 3.8918202, 1.3862944]],
      dtype=float32)>

In [56]:
tf.math.square(mean)

<tf.Tensor: id=119, shape=(3, 6), dtype=float32, numpy=
array([[ 1.,  4.,  9., 16., 25., 36.],
       [ 4.,  4.,  9., 16.,  9.,  4.],
       [ 1.,  4.,  1.,  1.,  4.,  1.]], dtype=float32)>

In [57]:
mean**2

<tf.Tensor: id=122, shape=(3, 6), dtype=float32, numpy=
array([[ 1.,  4.,  9., 16., 25., 36.],
       [ 4.,  4.,  9., 16.,  9.,  4.],
       [ 1.,  4.,  1.,  1.,  4.,  1.]], dtype=float32)>

In [58]:
inner = 1 + tf.math.log(var) - tf.math.square(mean) - tf.math.square(var)
inner

<tf.Tensor: id=130, shape=(3, 6), dtype=float32, numpy=
array([[-1.2924165e+03, -1.7613705e+01, -4.0998413e+03, -2.6822742e+02,
        -2.5000000e+01, -1.3274165e+03],
       [-4.0000000e+00, -2.5622742e+02, -4.0998413e+03, -6.3678113e+02,
        -9.0000000e+00, -8.1802773e+01],
       [-7.8802773e+01, -1.7613705e+01, -1.0000000e+00, -2.5322742e+02,
        -2.4001082e+03, -1.4613706e+01]], dtype=float32)>

In [59]:
inner = 1 + tf.math.log(var) - mean**2 - var**2
inner

<tf.Tensor: id=140, shape=(3, 6), dtype=float32, numpy=
array([[-1.2924165e+03, -1.7613705e+01, -4.0998413e+03, -2.6822742e+02,
        -2.5000000e+01, -1.3274165e+03],
       [-4.0000000e+00, -2.5622742e+02, -4.0998413e+03, -6.3678113e+02,
        -9.0000000e+00, -8.1802773e+01],
       [-7.8802773e+01, -1.7613705e+01, -1.0000000e+00, -2.5322742e+02,
        -2.4001082e+03, -1.4613706e+01]], dtype=float32)>

In [60]:
kls = tf.math.reduce_sum(inner, axis=1)
kls

<tf.Tensor: id=143, shape=(3,), dtype=float32, numpy=array([-7030.5156, -5087.653 , -2765.3657], dtype=float32)>

In [61]:
tf.math.reduce_mean(kls)

<tf.Tensor: id=146, shape=(), dtype=float32, numpy=-4961.1777>

In [62]:
def calculateKL(mean,std):
	inner = 1 + tf.math.log(std) - mean**2 - std**2
	kls = tf.math.reduce_sum(inner, axis=1)
	return tf.math.reduce_mean(kls)

In [63]:
calculateKL(mean, std)

<tf.Tensor: id=160, shape=(), dtype=float32, numpy=-155.75557>

In [159]:
probs = tf.constant([[0.1,0.2,0.7],
                      [0.3,0.2,0.5],
                      [0.1,0.5,0.4],
                      [0.1,0.8,0.1]])

In [160]:
def logit(p):
    return tf.log(p/(1-p))

In [162]:
logits = logit(probs)
logits

<tf.Tensor: id=688, shape=(4, 3), dtype=float32, numpy=
array([[-2.1972246 , -1.3862944 ,  0.84729785],
       [-0.8472978 , -1.3862944 ,  0.        ],
       [-2.1972246 ,  0.        , -0.40546516],
       [-2.1972246 ,  1.3862945 , -2.1972246 ]], dtype=float32)>

In [163]:
tf.sigmoid(logit(probs))

<tf.Tensor: id=694, shape=(4, 3), dtype=float32, numpy=
array([[0.09999996, 0.19999999, 0.7       ],
       [0.3       , 0.19999999, 0.5       ],
       [0.09999996, 0.5       , 0.4       ],
       [0.1       , 0.8       , 0.1       ]], dtype=float32)>

In [164]:
y_pred = tf.constant([[0.1,0.2,0.7],
                      [0.3,0.2,0.5],
                      [0.1,0.5,0.4],
                      [0.1,0.8,0.1]])

In [165]:
ber_dist = tf.distributions.Bernoulli(probs=y_pred)

In [166]:
y_true = tf.constant([[1.,0.,0.],
                      [0.,1.,0.],
                      [1.,0.,0.],
                      [0.,1.,0.]])

In [167]:
tf.nn.sigmoid_cross_entropy_with_logits(labels=y_true, logits=logits)

<tf.Tensor: id=712, shape=(4, 3), dtype=float32, numpy=
array([[2.3025851 , 0.22314355, 1.2039728 ],
       [0.35667497, 1.609438  , 0.6931472 ],
       [2.3025851 , 0.6931472 , 0.5108256 ],
       [0.10536051, 0.22314353, 0.10536051]], dtype=float32)>

In [169]:
-tf.reduce_sum(tf.nn.sigmoid_cross_entropy_with_logits(labels=y_true, logits=logits), axis=1)

<tf.Tensor: id=739, shape=(4,), dtype=float32, numpy=array([-3.7297015 , -2.65926   , -3.506558  , -0.43386453], dtype=float32)>

In [127]:
ber_dist.log_prob(y_true)

<tf.Tensor: id=545, shape=(3,), dtype=float32, numpy=array([-2.3025851 , -0.22314355, -1.2039728 ], dtype=float32)>

In [128]:
tf.exp(tf.reduce_sum(ber_dist.log_prob(1e-10 + y_true)))

<tf.Tensor: id=562, shape=(), dtype=float32, numpy=0.023999998>

In [129]:
1-y_true

<tf.Tensor: id=565, shape=(3,), dtype=float32, numpy=array([0., 1., 1.], dtype=float32)>

In [130]:
y_true*tf.log(y_pred) + (1-y_true)*tf.log(1-y_pred)

<tf.Tensor: id=575, shape=(3,), dtype=float32, numpy=array([-2.3025851 , -0.22314353, -1.2039728 ], dtype=float32)>

In [132]:
tf.exp(tf.reduce_sum(y_true*tf.log(y_pred) + (1-y_true)*tf.log(1-y_pred)))

<tf.Tensor: id=600, shape=(), dtype=float32, numpy=0.023999998>

In [79]:
0.9*0.8*0.7

0.504

In [66]:
np_a = np.array([[1,2,3,4,5],
                 [2,3,4,5,6],
                 [3,4,5,6,7]
                ])

In [67]:
np_y = np.array([1,2,3])

In [68]:
np_a

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [69]:
np_a[1:3]

array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [70]:
np_y[1:3]

array([2, 3])

In [174]:
tf.random.normal(
    shape=(1,5),
    mean=5.0,
    stddev=2.0
)

<tf.Tensor: id=760, shape=(1, 5), dtype=float32, numpy=
array([[5.192877 , 3.0717535, 5.164571 , 7.796317 , 4.1490183]],
      dtype=float32)>