In [1]:
import tensorflow as tf
import numpy as np

In [53]:
# Set Eager API
print("Setting Eager mode...")
tf.enable_eager_execution()
tfe = tf.contrib.eager

Setting Eager mode...


In [54]:
a = tf.constant([1., 2., 3., 4., 5., 6.], dtype=tf.float32)
a

<tf.Tensor: id=108, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [55]:
b = tf.constant([2., 3., 4., 5., 6., 7.], dtype=tf.float32)

In [56]:
sigma = tf.constant([2., 3., 4., 5., 6., 7.], dtype=tf.float32)

In [57]:
mu = tf.constant([1., 2., 3., 4., 5., 6.], dtype=tf.float32)

In [58]:
tf.math.reduce_sum(tf.math.square(a))

<tf.Tensor: id=115, shape=(), dtype=float32, numpy=91.0>

In [59]:
tf.reduce_sum(a*b)

<tf.Tensor: id=119, shape=(), dtype=float32, numpy=112.0>

In [60]:
tf.math.reduce_prod(a)

<tf.Tensor: id=122, shape=(), dtype=float32, numpy=720.0>

In [61]:
tf.math.reduce_sum(tf.math.log(a))

<tf.Tensor: id=126, shape=(), dtype=float32, numpy=6.5792513>

In [62]:
n=6

In [63]:
0.5*(- tf.math.reduce_sum(tf.math.log(sigma)) - n + tf.math.reduce_sum(sigma) + tf.math.reduce_sum(tf.math.square(mu)))

<tf.Tensor: id=142, shape=(), dtype=float32, numpy=51.73742>

In [64]:
tf.concat([a,b], 0)

<tf.Tensor: id=145, shape=(12,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 2., 3., 4., 5., 6., 7.], dtype=float32)>

In [65]:
print(tf.Print(a,[a],"a="))

tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32)


In [66]:
a

<tf.Tensor: id=108, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [67]:
t1 = tf.constant([[1.,2.],[1.,2.],[1.,2.]], dtype=tf.float32)
t1.shape
t1

<tf.Tensor: id=150, shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [1., 2.],
       [1., 2.]], dtype=float32)>

In [68]:
t2 = tf.constant([[3.,4.,5.,6.],[3.,4.,5.,6.],[3.,4.,5.,6.]], dtype=tf.float32)
t2.shape

TensorShape([Dimension(3), Dimension(4)])

In [69]:
tf.concat([t1,t2], 1).shape

TensorShape([Dimension(3), Dimension(6)])

In [70]:
aa = tf.constant([[1.,2.],[1.,2.],[1.,2.]], dtype=tf.float32)
bb = tf.constant([[5.,6.],[7.,8.],[9.,10.]], dtype=tf.float32)
aa + bb

<tf.Tensor: id=157, shape=(3, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [ 8., 10.],
       [10., 12.]], dtype=float32)>

In [71]:
tf.eye(10, num_columns=3)

<tf.Tensor: id=165, shape=(10, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [72]:
num_rows = 128
inferred_input_dim = 200

x_new_predictors_inferred = tf.ones([num_rows, inferred_input_dim], tf.float32)
x_given = tf.random.normal(
    shape=(num_rows, 3),
    mean=0.0,
    stddev=1.0,
    dtype=tf.float32,
    seed=None,
    name=None
)


In [73]:
x_all = tf.concat([x_given,x_new_predictors_inferred], 1)

In [74]:
x_all.shape[0].value




128

In [75]:
a

<tf.Tensor: id=108, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [76]:
e = tf.eye(6)

In [77]:
a*e

<tf.Tensor: id=183, shape=(6, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0.],
       [0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 6.]], dtype=float32)>

In [78]:
b

<tf.Tensor: id=110, shape=(6,), dtype=float32, numpy=array([2., 3., 4., 5., 6., 7.], dtype=float32)>

In [79]:
tf.math.multiply(a,b)

<tf.Tensor: id=186, shape=(6,), dtype=float32, numpy=array([ 2.,  6., 12., 20., 30., 42.], dtype=float32)>

In [80]:
a*b

<tf.Tensor: id=188, shape=(6,), dtype=float32, numpy=array([ 2.,  6., 12., 20., 30., 42.], dtype=float32)>

In [81]:
f = tf.ones(6, tf.float32)

In [82]:
f

<tf.Tensor: id=192, shape=(6,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1.], dtype=float32)>

In [83]:
a*f

<tf.Tensor: id=194, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [84]:
x = tf.constant([[1.,1.,1.,1.,1.,1.],[2.,2.,2.,2.,2.,2.],[3.,3.,3.,3.,3.,3.]], dtype=tf.float32)
x.shape

TensorShape([Dimension(3), Dimension(6)])

In [85]:
y = tf.constant([[1.,1.,1.],[2.,2.,2.],[3.,3.,3.]], dtype=tf.float32)
y.shape

TensorShape([Dimension(3), Dimension(3)])

In [86]:
a1 = tf.constant([1., 2., 3., 4., 5., 6.], dtype=tf.float32)
a2 = tf.constant([1., 2., 3.], dtype=tf.float32)

In [87]:
r1 = x*a1

In [88]:
r2 = y*a2

In [89]:
tf.concat([r1,r2], axis=1)

<tf.Tensor: id=203, shape=(3, 9), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.,  1.,  2.,  3.],
       [ 2.,  4.,  6.,  8., 10., 12.,  2.,  4.,  6.],
       [ 3.,  6.,  9., 12., 15., 18.,  3.,  6.,  9.]], dtype=float32)>

In [90]:
x_small = tf.constant([[1.,1.,1.,1.,1.,1.]], dtype=tf.float32)
x_small.shape

TensorShape([Dimension(1), Dimension(6)])

In [91]:
y_small = tf.constant([[1.,1.,1.]], dtype=tf.float32)
y_small.shape

TensorShape([Dimension(1), Dimension(3)])

In [92]:
r1_small = x_small*a1

In [93]:
r2_small = y_small*a2

In [94]:
r1_small,r2_small

(<tf.Tensor: id=207, shape=(1, 6), dtype=float32, numpy=array([[1., 2., 3., 4., 5., 6.]], dtype=float32)>,
 <tf.Tensor: id=208, shape=(1, 3), dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>)

In [95]:
tf.concat([r1_small,r2_small], axis=1)

<tf.Tensor: id=212, shape=(1, 9), dtype=float32, numpy=array([[1., 2., 3., 4., 5., 6., 1., 2., 3.]], dtype=float32)>

In [96]:
a


<tf.Tensor: id=108, shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [97]:
a.shape[0].value

6

In [128]:
mean = tf.constant([[1., 2., 3., 4., 5., 6.],
                    [2., 2., 3., 4., 3., 2.],
                    [1., 2., 1., 1., 2., 1.]
                   ]
                    , dtype=tf.float32)
std = tf.constant([[6., 2., 8., 4., 1., 6.],
                   [1., 4., 8., 5., 1., 3.],
                   [3., 2., 1., 4., 7., 2.]
                  ]
                  , dtype=tf.float32)

In [106]:
mean

<tf.Tensor: id=230, shape=(3, 6), dtype=float32, numpy=
array([[1., 2., 3., 4., 5., 6.],
       [2., 2., 3., 4., 3., 2.],
       [1., 2., 1., 1., 2., 1.]], dtype=float32)>

In [107]:
var

<tf.Tensor: id=231, shape=(3, 6), dtype=float32, numpy=
array([[6., 2., 8., 4., 1., 6.],
       [1., 4., 8., 5., 1., 3.],
       [3., 2., 1., 4., 7., 2.]], dtype=float32)>

In [110]:
tf.math.log(var)

<tf.Tensor: id=254, shape=(3, 6), dtype=float32, numpy=
array([[1.7917595, 0.6931472, 2.0794415, 1.3862944, 0.       , 1.7917595],
       [0.       , 1.3862944, 2.0794415, 1.609438 , 0.       , 1.0986123],
       [1.0986123, 0.6931472, 0.       , 1.3862944, 1.9459101, 0.6931472]],
      dtype=float32)>

In [111]:
tf.math.square(mean)

<tf.Tensor: id=256, shape=(3, 6), dtype=float32, numpy=
array([[ 1.,  4.,  9., 16., 25., 36.],
       [ 4.,  4.,  9., 16.,  9.,  4.],
       [ 1.,  4.,  1.,  1.,  4.,  1.]], dtype=float32)>

In [112]:
mean**2

<tf.Tensor: id=259, shape=(3, 6), dtype=float32, numpy=
array([[ 1.,  4.,  9., 16., 25., 36.],
       [ 4.,  4.,  9., 16.,  9.,  4.],
       [ 1.,  4.,  1.,  1.,  4.,  1.]], dtype=float32)>

In [122]:
inner = 1 + tf.math.log(var) - tf.math.square(mean) - tf.math.square(var)
inner

<tf.Tensor: id=319, shape=(3, 6), dtype=float32, numpy=
array([[-34.20824  ,  -6.306853 , -69.920555 , -29.613705 , -25.       ,
        -69.20824  ],
       [ -4.       , -17.613705 , -69.920555 , -38.390564 ,  -9.       ,
        -10.901388 ],
       [ -7.9013877,  -6.306853 ,  -1.       , -14.613706 , -50.05409  ,
         -3.3068528]], dtype=float32)>

In [125]:
inner = 1 + tf.math.log(var) - mean**2 - var**2
inner

<tf.Tensor: id=335, shape=(3, 6), dtype=float32, numpy=
array([[-34.20824  ,  -6.306853 , -69.920555 , -29.613705 , -25.       ,
        -69.20824  ],
       [ -4.       , -17.613705 , -69.920555 , -38.390564 ,  -9.       ,
        -10.901388 ],
       [ -7.9013877,  -6.306853 ,  -1.       , -14.613706 , -50.05409  ,
         -3.3068528]], dtype=float32)>

In [126]:
kls = tf.math.reduce_sum(inner, axis=1)
kls

<tf.Tensor: id=338, shape=(3,), dtype=float32, numpy=array([-234.2576 , -149.8262 ,  -83.18289], dtype=float32)>

In [127]:
tf.math.reduce_mean(kls)

<tf.Tensor: id=341, shape=(), dtype=float32, numpy=-155.75557>

In [ ]:
def calculateKL(mean,std):
	inner = 1 + tf.math.log(std) - mean**2 - std**2
	kls = tf.math.reduce_sum(inner, axis=1)
	return tf.math.reduce_mean(kls)

In [130]:
calculateKL(mean, std)

<tf.Tensor: id=357, shape=(), dtype=float32, numpy=-155.75557>

In [139]:

ber_dist = tf.distributions.Bernoulli(probs=[0.1,0.2,0.7])

In [142]:
ber_dist.prob([0.,0.,0.5])

<tf.Tensor: id=480, shape=(3,), dtype=float32, numpy=array([0.90000004, 0.8       , 0.4582576 ], dtype=float32)>

In [145]:
np_a = np.array([[1,2,3,4,5],
                 [2,3,4,5,6],
                 [3,4,5,6,7]
                ])

In [148]:
np_y = np.array([1,2,3])

In [146]:
np_a

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [150]:
np_a[1:3]

array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [151]:
np_y[1:3]

array([2, 3])